apiVersion: v1
kind: Service
metadata:
  name: {{ include "rawfile-localpv.fullname" . }}-controller
  labels:
    {{- include "rawfile-localpv.labels" . | nindent 4 }}
    component: controller
spec:
  type: ClusterIP
  selector:
    {{- include "rawfile-localpv.selectorLabels" . | nindent 4 }}
    component: controller
  clusterIP: None
