apiVersion: v2
appVersion: 0.12.0
dependencies:
- condition: crds.enabled
  name: crds
  repository: ""
  version: 0.0.1
description: RawFile Driver Container Storage Interface
home: https://openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- filesystem
- sparse
- rawfile
- Local Persistent Volumes
- storage
kubeVersion: '>= 1.21'
name: rawfile-localpv
sources:
- https://github.com/openebs/rawfile-localpv
type: application
version: 0.12.0
