apiVersion: v1
kind: Service
metadata:
  name: {{ include "rawfile-localpv.fullname" . }}-node
  labels:
    {{- include "rawfile-localpv.labels" . | nindent 4 }}
    component: node
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    - name: internal
      port: {{ .Values.node.internalGRPC.port }}
      protocol: TCP
  selector:
    {{- include "rawfile-localpv.selectorLabels" . | nindent 4 }}
    component: node
