annotations:
  artifacthub.io/changes: |
    - "tests(hub): relocate and clean api gw tests"
    - "fix(grpc): enforce mutually exclusive TLS and insecure options"
    - "fix(chart): allow to be used as optional subchart"
    - "fix(chart): add nameOverride and fullnameOverride to schema file"
    - "fix(api): add support for missing insecure and debug options"
    - "feat(deps): update traefik docker tag to v3.6.8"
    - "feat(deployment): support templating for podLabels"
    - "docs(schema): add description from helm-docs comments"
    - "chore(release): publish v39.0.1"
apiVersion: v2
appVersion: v3.6.8
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 39.0.1
